### ISSUE TITLE
Lomiri+ --- Hide notification content when locked

### ISSUE THREAD

**Issue by bigbrotherisstillwatching** [kugiigi/jerk-packages#38]
Security & Privacy -> Hide notification content when locked

This is already implemented in the system (Ubuntu Touch Focal OTA-5 Stable), isn't it?

**Comment by kugiigi** [comment]
That only affects the notification bubble. This one affects the list in the indicator panel.

**Comment by bigbrotherisstillwatching** [comment]
Understood.
